### ISSUE TITLE
Aling items doesn't work

### ISSUE THREAD

**Issue by Fidius-jko** [RibirX/Ribir#587]
**Problem**

**Steps To Reproduce**
write this code and run: 
``` rust
use ribir::prelude::*;

fn main() {
    App::run(fn_widget! {
    rdl!{
      Row {
        align_items: Align::Center,
        rdl!{ FilledButton {
          rdl!{ Label::new("Increment") }
        }}
        rdl!{ H1 { text: "0" } }
      }
    }
  });
}
```

**Expected behavior**
Button and H1 are at center

**Screenshots**
![image](https://github.com/RibirX/Ribir/assets/95738553/f1e19e40-9dd9-44c1-a7a1-7e2ad509bb74)

**Environment:**
 - Ribir version: [`0.2.0-beta.1`]
 - Rust version: [`nightly`]
 - OS, if relevant: [Win10]

**Comment by M-Adoo** [comment]
Hi, @Fidius-jko 

The `align_items` property determines the placement of child widgets along the cross axis in a flex layout.

In your scenario, it positions the two child widgets of the `Row` widget at the vertical center of the `Row` widget. Since the `Row` is expanded by the Button and the H1, the H1 is positioned at the vertical center of the Row, which is the expected behavior.

If you wish to center the entire `Row` relative to its parent widget (in this case, the window), you can use the built-in properties `h_align` and `v_align`.
